apiVersion: v1
kind: Service
metadata:
  name: fcg-payments-service
  namespace: fcg-payments
spec:
  selector:
    app: fcg-payments-service
  ports:
    - protocol: TCP
      port: ${SERVICE_PORT}
      targetPort: ${CONTAINER_PORT}
  type: ClusterIP
